 

package Reports;

import ModuleFrames.*;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.*;
import utils.userDao;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.PasswordAuthentication;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Statement;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import utils.DBUtils;

/**
 *
 * @author Dilip Library Module Class
 */
public class DefaulterJFrame extends javax.swing.JFrame {

    ResultSet rs = null;       
    PreparedStatement pst=null;
    private Connection con;
    ArrayList<String> studIdList = new ArrayList<String>();
    ArrayList<String> studName = new ArrayList<String>();
    ArrayList<String> mobileNoList = new ArrayList<String>();
    ArrayList<Double> totalDuesList = new ArrayList<Double>();
    static  String studID;
    static String studentName;
    static String  mobileno;
    static Double finalDues;
    public DefaulterJFrame() {
        initComponents();
        con=userDao.getConnection();
        getDefaulterData();
        
    }
/*
    Method to fetch data from Student , Library and hostel
    
    */
private void getDefaulterData()
{
            try
            {
                
                String sql = "SELECT s.StudentID as StudentID,s.StudentName,s.Semester,s.Email,s.Mobile as Mobile,l.Fine as LibraryFine,h.Fine as HostelFine,s.TotalDues as TotalDues\n" +
                             "FROM student as s\n" +
                             "RIGHT JOIN library as l\n" +
                             "ON s.StudentID = l.StudentID\n" +
                             "RIGHT JOIN hostel as h\n" +
                             "ON s.StudentID = h.StudentID and  l.StudentID = h.StudentID";
                System.out.println( "::Defaulter Query:::"+sql);
                pst = con.prepareStatement(sql);               
                rs = pst.executeQuery();
                table_Student.setModel(DbUtils.resultSetToTableModel(rs));
               
                System.err.println( new Date().toString()+"::Defaulter MODULE:::");
                System.err.println( new Date().toString()+"::Defulter Query:::"+sql);
                
            }
            catch (Exception e)
            {
                System.err.println( new Date().toString()+"::Not Connected !!!!"+e.getMessage());                         
            }
            finally
            {
                try {
                    rs.close();
                    pst.close();
                } 
                catch (SQLException ex) {
                    
                     System.err.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                    
                }
            }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librarayJFrame1 = new ModuleFrames.LibrarayJFrame();
        label_Heading = new javax.swing.JLabel();
        btn_Sms = new javax.swing.JButton();
        btn_ExportToExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Student = new javax.swing.JTable();
        label_LibraryMainFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Defulaters Report");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(400, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        label_Heading.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        label_Heading.setForeground(new java.awt.Color(255, 255, 255));
        label_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Heading.setText("Defaulter Students List");
        getContentPane().add(label_Heading);
        label_Heading.setBounds(440, 30, 420, 50);

        btn_Sms.setText("SEND REMINDER TO ALL");
        btn_Sms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SmsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sms);
        btn_Sms.setBounds(220, 300, 220, 30);

        btn_ExportToExcel.setText("EXPORT TO EXCEL");
        btn_ExportToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportToExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ExportToExcel);
        btn_ExportToExcel.setBounds(470, 300, 220, 30);

        table_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Student.setMaximumSize(new java.awt.Dimension(200, 64));
        table_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_StudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Student);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 120, 770, 120);

        label_LibraryMainFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginbg.jpg"))); // NOI18N
        label_LibraryMainFrame.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                label_LibraryMainFrameComponentAdded(evt);
            }
        });
        getContentPane().add(label_LibraryMainFrame);
        label_LibraryMainFrame.setBounds(0, 0, 1350, 510);
        label_LibraryMainFrame.getAccessibleContext().setAccessibleName("Library Main Frame");

        getAccessibleContext().setAccessibleParent(label_LibraryMainFrame);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_StudentMouseClicked
        
       
    }//GEN-LAST:event_table_StudentMouseClicked
/**/
    
    
    
    // End no of days method
    private void label_LibraryMainFrameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_label_LibraryMainFrameComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_label_LibraryMainFrameComponentAdded

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
        setSize(1200, 500);
        setLocation(60, 100);
    }//GEN-LAST:event_formComponentResized

    private void btn_SmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SmsActionPerformed
        
        try
            {
                
                String sql = "SELECT s.StudentID as StudentID,s.StudentName as StudentName,s.Semester,s.Email,s.Mobile as Mobile,l.Fine as LibraryFine,h.Fine as HostelFine,s.TotalDues as TotalDues\n" +
                             "FROM student as s\n" +
                             "RIGHT JOIN library as l\n" +
                             "ON s.StudentID = l.StudentID\n" +
                             "RIGHT JOIN hostel as h\n" +
                             "ON s.StudentID = h.StudentID and  l.StudentID = h.StudentID";
                System.out.println( "::Defaulter Query:::"+sql);
                pst = con.prepareStatement(sql);               
                rs = pst.executeQuery();              
                
                while(rs.next()){
                    studID  = rs.getString("StudentID");
                    studentName = rs.getString("StudentName");
                    mobileno = rs.getString("Mobile");
                    finalDues  = rs.getDouble("TotalDues");
	            studIdList.add(studID);
                    studName.add(studentName);
                    mobileNoList.add(mobileno);
                    totalDuesList.add(finalDues);
	         }
                
                System.out.println( studIdList.size()+"::Student ID LIST :::");
                System.out.println( mobileNoList.size()+"::mobileNoList LIST :::");
                System.out.println( totalDuesList.size()+"::Student ID LIST :::");
                System.err.println( new Date().toString()+"::Defaulter MODULE:::");
                System.err.println( new Date().toString()+"::Defulter Query:::"+sql);
                
            }
            catch (Exception e)
            {
                System.err.println( new Date().toString()+"::Not Connected !!!!"+e.getMessage());                         
            }
            finally
            {
                try {
                    rs.close();
                    pst.close();
                } 
                catch (SQLException ex) {
                    
                     System.err.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                    
                }
            }
                
        int count =0;
        
        for (int i = 0; i<studIdList.size();i++)
        {
             boolean result=sendSms(mobileNoList.get(i),studName.get(i),totalDuesList.get(i).toString());
             count ++;
             if(result)
             {
                 System.out.println("Message sent succesfully");   
             }
             else
             {
                    System.out.println( new Date().toString()+"::Error Sending Message !");
                    JOptionPane.showMessageDialog(null,"Error Sending SMS.");
             }
              JOptionPane.showMessageDialog(null,"Message Sent Successfully.");
        }
        
        System.out.println( new Date().toString()+":::Count Value"+count);
    }//GEN-LAST:event_btn_SmsActionPerformed

    private void btn_ExportToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportToExcelActionPerformed
                 DefaulterJFrame defJframe = new DefaulterJFrame();
                defJframe.getExcelFile();
    }//GEN-LAST:event_btn_ExportToExcelActionPerformed

         public static boolean sendSms(String mobile,String name,String dues)
	{
            String data = "";
	    StringBuffer messageContent = new StringBuffer("");
            messageContent.append("Dear +"+name+"");
            messageContent.append("+ Rs.+"+dues+" +left+to+be+paid.+");
            messageContent.append("+Kindly+pay+your+dues.+");
            messageContent.append("+-+College+Accountant");
            
          
            try
            {
                String url = "http://smsworld.way2webworld.com/sendsms.php?username=apiit&password=letmein&sender=Default&mobile="+mobile+"&message="+messageContent+"&route=P";
		String smsApiResponse = sendMySMS(url);
		System.out.println(smsApiResponse);                           
            }
            catch (Exception e)
            {
                e.printStackTrace();
                return false;
            }
            
           
            return true;
        }
         
         public static String sendMySMS(String url){
	    StringBuilder output = new StringBuilder();
	    try{
	      URL hp = new URL(url);
	      System.out.println(url);
	      URLConnection hpCon = hp.openConnection(); 
	      BufferedReader in = new BufferedReader(new InputStreamReader(hpCon.getInputStream()));
	      String inputLine;
	      while ((inputLine = in.readLine()) != null)
	        output.append(inputLine);
	      in.close();
	    }catch (Exception e) {
	      e.printStackTrace();
	    }
	    return output.toString();
	  }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentJFrame().setVisible(true);
            }
        });
    }
    
    /*
     Method to generate Excel File for Defaulters
    */
     public  void getExcelFile()
        {
                    try
                    {           
                    String filename="DefaulterList.xls" ;
                    HSSFWorkbook hwb=new HSSFWorkbook();
                    HSSFSheet sheet =  hwb.createSheet("new sheet");

                    HSSFRow rowhead=   sheet.createRow((short)0);
                    rowhead.createCell((short) 0).setCellValue("Student ID");
                    rowhead.createCell((short) 1).setCellValue("Student Name");
                    rowhead.createCell((short) 2).setCellValue("Semester");
                    rowhead.createCell((short) 3).setCellValue("Email");
                    rowhead.createCell((short) 4).setCellValue("Mobile");
                    rowhead.createCell((short) 5).setCellValue("Library Fine");
                    rowhead.createCell((short) 6).setCellValue("Hostel Fine");
                    rowhead.createCell((short) 7).setCellValue("Total Dues");
                    
                     String sql = "SELECT s.StudentID as StudentID,s.StudentName,s.Semester,s.Email,s.Mobile as Mobile,l.Fine as LibraryFine,h.Fine as HostelFine,s.TotalDues as TotalDues\n" +
                             "FROM student as s\n" +
                             "RIGHT JOIN library as l\n" +
                             "ON s.StudentID = l.StudentID\n" +
                             "RIGHT JOIN hostel as h\n" +
                             "ON s.StudentID = h.StudentID and  l.StudentID = h.StudentID where s.TotalDues>0";
                    System.out.println( "::Defaulter Query:::"+sql);
                    pst = con.prepareStatement(sql);               
                    rs = pst.executeQuery();
                    
                    int i=1;
                    while(rs.next()){
                    HSSFRow row=   sheet.createRow((short)i);
                    row.createCell((short) 0).setCellValue(rs.getString("StudentID"));
                    row.createCell((short) 1).setCellValue(rs.getString("StudentName"));
                    row.createCell((short) 2).setCellValue(rs.getString("Semester"));                    
                    row.createCell((short) 3).setCellValue(rs.getString("Email"));
                    row.createCell((short) 4).setCellValue(rs.getString("Mobile"));
                    row.createCell((short) 5).setCellValue(rs.getString("LibraryFine"));
                    row.createCell((short) 6).setCellValue(rs.getString("HostelFine"));
                    row.createCell((short) 7).setCellValue(rs.getString("TotalDues"));
                    i++;
                }
                FileOutputStream fileOut =  new FileOutputStream(filename);
                hwb.write(fileOut);
                fileOut.close();
                System.out.println("Your excel file has been generated!");

        }           
                 catch ( Exception ex ) {
                 System.out.println(ex);
                 ex.printStackTrace();

            }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ExportToExcel;
    private javax.swing.JButton btn_Sms;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Heading;
    private javax.swing.JLabel label_LibraryMainFrame;
    private ModuleFrames.LibrarayJFrame librarayJFrame1;
    private javax.swing.JTable table_Student;
    // End of variables declaration//GEN-END:variables
}
