package ModuleFrames;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import utils.userDao;

/**
@author Dilip Pc
 */

public class BusJFrame extends javax.swing.JFrame {

    ResultSet rs = null;       
    PreparedStatement pst=null;
    private Connection con;
    public BusJFrame() {
        initComponents();
        con=userDao.getConnection();
        getBusData();
    }
    
     
private void getBusData()
{
    try
            {
                String sql = "select * from bus";
                pst = con.prepareStatement(sql);               
                rs = pst.executeQuery();                
                tabelBus.setModel(DbUtils.resultSetToTableModel(rs));
                
            }
            catch (Exception e)
            {
                System.err.println( new Date().toString()+"::Error while fetching Bus Module data!!!!"+e.getMessage());
                
            }
            finally
            {
                try {
                    rs.close();
                    pst.close();
                } 
                catch (SQLException ex) {
                    
                     System.err.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                    
                }
            }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_studentID = new javax.swing.JLabel();
        txt_studentID = new javax.swing.JTextField();
        label_busFee = new javax.swing.JLabel();
        label_busNumber = new javax.swing.JLabel();
        label_serviceCost = new javax.swing.JLabel();
        label_serviceDate = new javax.swing.JLabel();
        label_busRoute = new javax.swing.JLabel();
        label_accidentCost = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_busNumber = new javax.swing.JTextField();
        txt_busFee = new javax.swing.JTextField();
        txt_serviceCost = new javax.swing.JTextField();
        txt_accidentCost = new javax.swing.JTextField();
        jDate_accident = new com.toedter.calendar.JDateChooser();
        btn_Update = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();
        btn_Enter = new javax.swing.JButton();
        txt_busRoute = new javax.swing.JTextField();
        jDate_Service = new com.toedter.calendar.JDateChooser();
        label_HeadingBus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBus = new javax.swing.JTable();
        label_BusMainFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bus Module Frame");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        label_studentID.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_studentID.setForeground(new java.awt.Color(255, 255, 255));
        label_studentID.setText("Student ID");
        getContentPane().add(label_studentID);
        label_studentID.setBounds(20, 120, 110, 20);
        getContentPane().add(txt_studentID);
        txt_studentID.setBounds(140, 120, 110, 20);

        label_busFee.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_busFee.setForeground(new java.awt.Color(255, 255, 255));
        label_busFee.setText("Bus Fee");
        getContentPane().add(label_busFee);
        label_busFee.setBounds(20, 160, 110, 20);

        label_busNumber.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_busNumber.setForeground(new java.awt.Color(255, 255, 255));
        label_busNumber.setText("Bus Number");
        getContentPane().add(label_busNumber);
        label_busNumber.setBounds(20, 240, 110, 20);

        label_serviceCost.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_serviceCost.setForeground(new java.awt.Color(255, 255, 255));
        label_serviceCost.setText("Service Cost");
        getContentPane().add(label_serviceCost);
        label_serviceCost.setBounds(20, 280, 110, 20);

        label_serviceDate.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_serviceDate.setForeground(new java.awt.Color(255, 255, 255));
        label_serviceDate.setText("Service Date");
        getContentPane().add(label_serviceDate);
        label_serviceDate.setBounds(20, 320, 110, 20);

        label_busRoute.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_busRoute.setForeground(new java.awt.Color(255, 255, 255));
        label_busRoute.setText("Bus Route");
        getContentPane().add(label_busRoute);
        label_busRoute.setBounds(20, 200, 110, 20);

        label_accidentCost.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_accidentCost.setForeground(new java.awt.Color(255, 255, 255));
        label_accidentCost.setText("Accident Cost");
        getContentPane().add(label_accidentCost);
        label_accidentCost.setBounds(20, 360, 110, 20);

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Accident Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 400, 110, 20);

        txt_busNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txt_busNumber);
        txt_busNumber.setBounds(140, 240, 110, 20);

        txt_busFee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busFeeKeyTyped(evt);
            }
        });
        getContentPane().add(txt_busFee);
        txt_busFee.setBounds(140, 160, 110, 20);

        txt_serviceCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serviceCostKeyTyped(evt);
            }
        });
        getContentPane().add(txt_serviceCost);
        txt_serviceCost.setBounds(140, 280, 110, 20);

        txt_accidentCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_accidentCostKeyTyped(evt);
            }
        });
        getContentPane().add(txt_accidentCost);
        txt_accidentCost.setBounds(140, 360, 110, 20);
        getContentPane().add(jDate_accident);
        jDate_accident.setBounds(140, 400, 110, 20);

        btn_Update.setText("UPDATE");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Update);
        btn_Update.setBounds(40, 500, 110, 30);

        btn_Refresh.setText("REFRESH");
        btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Refresh);
        btn_Refresh.setBounds(200, 500, 110, 30);

        btn_Enter.setText("Enter");
        btn_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Enter);
        btn_Enter.setBounds(260, 120, 100, 23);
        getContentPane().add(txt_busRoute);
        txt_busRoute.setBounds(140, 200, 110, 20);
        getContentPane().add(jDate_Service);
        jDate_Service.setBounds(140, 320, 110, 20);

        label_HeadingBus.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        label_HeadingBus.setForeground(new java.awt.Color(255, 255, 255));
        label_HeadingBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_HeadingBus.setText("Bus Module");
        label_HeadingBus.setMaximumSize(new java.awt.Dimension(196, 28));
        label_HeadingBus.setMinimumSize(new java.awt.Dimension(196, 28));
        label_HeadingBus.setPreferredSize(new java.awt.Dimension(196, 28));
        getContentPane().add(label_HeadingBus);
        label_HeadingBus.setBounds(500, 40, 200, 40);

        tabelBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBus.setMaximumSize(new java.awt.Dimension(120, 64));
        tabelBus.setPreferredSize(new java.awt.Dimension(200, 64));
        tabelBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBus);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 120, 770, 100);

        label_BusMainFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginbg.jpg"))); // NOI18N
        label_BusMainFrame.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                label_BusMainFrameComponentResized(evt);
            }
        });
        getContentPane().add(label_BusMainFrame);
        label_BusMainFrame.setBounds(0, 0, 1170, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setSize(1175, 600);
        setLocation(100, 100);
    }//GEN-LAST:event_formComponentResized

    private void label_BusMainFrameComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_label_BusMainFrameComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_label_BusMainFrameComponentResized

    private void txt_busNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busNumberActionPerformed

    private void tabelBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBusMouseClicked
          try
       {
            int row = tabelBus.getSelectedRow();
            String Table_Click = (tabelBus.getModel().getValueAt(row, 0).toString());
            String sql = " select * from bus where StudentId = '"+Table_Click+"'";
            pst = con.prepareStatement (sql);
	    rs=pst.executeQuery(sql);
            if(rs.next())
            {
               String studID = rs.getString("StudentId");
               txt_studentID.setText(studID);         
           
               
               String busFee = rs.getDouble("BusFee")+"";
               txt_busFee.setText(busFee);
               
               String busRoute = rs.getString("BusRoute");
               txt_busRoute.setText(busRoute);  
               
               String busNumber = rs.getString("BusNumber");
               txt_busNumber.setText(busNumber); 
               
               String serviceCost = rs.getDouble("ServiceCost")+"";
               txt_serviceCost.setText(serviceCost); 
               
               java.util.Date serviceDate = rs.getDate("ServiceDate") ;
               jDate_Service.setDate(serviceDate); 
               
               String accidentCost = rs.getDouble("AccidentCost")+"";
               txt_accidentCost.setText(accidentCost);
               
               java.util.Date accidentDate = rs.getDate("AccidentDate") ;
               jDate_accident.setDate(accidentDate); 
           
         }
                  
       }
       catch (Exception e)
       {
           System.err.println( new Date().toString()+"::Not Connected!!!!"+e.getMessage());
           
       }
         finally
            {
                try {
                    rs.close();
                    pst.close();
                } 
                catch (SQLException ex) {
                    System.err.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                   
                }
            }
    }//GEN-LAST:event_tabelBusMouseClicked

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
         txt_studentID.setText("");
         txt_busFee.setText("");
         txt_busNumber.setText("");
         txt_busRoute.setText("");
         txt_serviceCost.setText("");
         txt_accidentCost.setText("");
    }//GEN-LAST:event_btn_RefreshActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        try
       {
                    
            String studentID = txt_studentID.getText();             
            String busFee = txt_busFee.getText();
            String busRoute =  txt_busRoute.getText();
            String busNumber =  txt_busNumber.getText();
            String serviceCost  =  txt_serviceCost.getText();
            Date serviceDate = jDate_Service.getDate();
            String accidentCost  = txt_accidentCost.getText();
            Date accidentDate = jDate_accident.getDate();
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            String serviceDateFinal = dateFormat.format(serviceDate).toString();
            String accidentDateFinal = dateFormat.format(accidentDate).toString();
            
            System.out.println("service Date"+serviceDate + ":::AccidentDate ::"+accidentDate);
            String sql = "update bus set BusFee = '"+busFee+"', BusRoute = '"+busRoute+"' , BusNumber = '"+busNumber+"', ServiceCost = '"+serviceCost+"', ServiceDate = '"+serviceDateFinal+"' , AccidentCost = '"+accidentCost+"', AccidentDate = '"+accidentDateFinal+"' where StudentId = '"+studentID+"'";
            pst = con.prepareStatement(sql);
            pst.execute();
            System.err.println( new Date().toString()+"::Update Query!!!!"+sql);
            
            JOptionPane.showMessageDialog(null,"Details Updated");
                  
       }
       catch (Exception e)
       {
           System.err.println( new Date().toString()+"::Not Connected UPDATION!!!!"+e.getMessage());
                    
       }
            finally
            {
                try {
                    rs.close();
                    pst.close();
                } 
                catch (SQLException ex) {
                    System.err.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                    
                }
            }
       getBusData();
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void txt_busFeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busFeeKeyTyped
         char c = evt.getKeyChar();
          if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
              evt.consume();
          }
    }//GEN-LAST:event_txt_busFeeKeyTyped

    private void txt_serviceCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serviceCostKeyTyped
         char c = evt.getKeyChar();
          if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
              evt.consume();
          }
    }//GEN-LAST:event_txt_serviceCostKeyTyped

    private void txt_accidentCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_accidentCostKeyTyped
         char c = evt.getKeyChar();
          if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
              evt.consume();
          }
    }//GEN-LAST:event_txt_accidentCostKeyTyped

    private void btn_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnterActionPerformed
          try
       {
            String studID = txt_studentID.getText();              
            String sql = " select * from bus where StudentId = '"+studID+"'";
            pst = con.prepareStatement (sql);
	    rs=pst.executeQuery(sql);
            if(rs.next())
            {                             
               String busFee = rs.getDouble("BusFee")+"";
               txt_busFee.setText(busFee);
               
               String busRoute = rs.getString("BusRoute");
               txt_busRoute.setText(busRoute);  
               
               String busNumber = rs.getString("BusNumber");
               txt_busNumber.setText(busNumber); 
               
               String serviceCost = rs.getDouble("ServiceCost")+"";
               txt_serviceCost.setText(serviceCost); 
               
               java.util.Date serviceDate = rs.getDate("ServiceDate") ;
               jDate_Service.setDate(serviceDate); 
               
               String accidentCost = rs.getDouble("AccidentCost")+"";
               txt_accidentCost.setText(accidentCost);
               
               java.util.Date accidentDate = rs.getDate("AccidentDate") ;
               jDate_accident.setDate(accidentDate);            
         }
            else
            {
                JOptionPane.showMessageDialog(null,"Student ID Incorrect !");
            }
                  
       }
       catch (Exception e)
       {
           System.err.println( new Date().toString()+"::Not Connected!!!!"+e.getMessage());
           
       }
         finally
            {
                try {
                    rs.close();
                    pst.close();
                } 
                catch (SQLException ex) {
                    System.err.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                   
                }
            }
    }//GEN-LAST:event_btn_EnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Enter;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JButton btn_Update;
    private com.toedter.calendar.JDateChooser jDate_Service;
    private com.toedter.calendar.JDateChooser jDate_accident;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_BusMainFrame;
    private javax.swing.JLabel label_HeadingBus;
    private javax.swing.JLabel label_accidentCost;
    private javax.swing.JLabel label_busFee;
    private javax.swing.JLabel label_busNumber;
    private javax.swing.JLabel label_busRoute;
    private javax.swing.JLabel label_serviceCost;
    private javax.swing.JLabel label_serviceDate;
    private javax.swing.JLabel label_studentID;
    private javax.swing.JTable tabelBus;
    private javax.swing.JTextField txt_accidentCost;
    private javax.swing.JTextField txt_busFee;
    private javax.swing.JTextField txt_busNumber;
    private javax.swing.JTextField txt_busRoute;
    private javax.swing.JTextField txt_serviceCost;
    private javax.swing.JTextField txt_studentID;
    // End of variables declaration//GEN-END:variables
}
