package ModuleFrames;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import net.proteanit.sql.DbUtils;
import utils.userDao;
import javax.swing.JOptionPane;

/**
@author Dilip Pc
 */

public class DonationJFrame extends javax.swing.JFrame {

    ResultSet rs = null;       
    PreparedStatement pst=null;
    private Connection con;
    public DonationJFrame() {
        initComponents();
        con=userDao.getConnection();
        getDonationData();
    }
    
    private void getDonationData()
{
    try
            {
                String sql = "select * from donation";
                pst = con.prepareStatement(sql);               
                rs = pst.executeQuery();                
                table_Donation.setModel(DbUtils.resultSetToTableModel(rs));
                
            }
            catch (Exception e)
            {
                System.err.println( new Date().toString()+"::Error while fetching Doantion data!!!!"+e.getMessage());
                
            }
            finally
            {
                try {
                    rs.close();
                    pst.close();
                } 
                catch (SQLException ex) {
                    
                     System.err.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                    
                }
            }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_DonationHeading = new javax.swing.JLabel();
        label_Amount = new javax.swing.JLabel();
        label_Cheque = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JTextField();
        txt_Cheque = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        btn_Insert = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Donation = new javax.swing.JTable();
        label_DonationMainFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Donation Module Frame");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        label_DonationHeading.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        label_DonationHeading.setForeground(new java.awt.Color(255, 255, 255));
        label_DonationHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_DonationHeading.setText("DONATION MODULE");
        getContentPane().add(label_DonationHeading);
        label_DonationHeading.setBounds(310, 30, 223, 40);

        label_Amount.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_Amount.setForeground(new java.awt.Color(255, 255, 255));
        label_Amount.setText("Amount");
        getContentPane().add(label_Amount);
        label_Amount.setBounds(30, 100, 110, 20);

        label_Cheque.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        label_Cheque.setForeground(new java.awt.Color(255, 255, 255));
        label_Cheque.setText("Cheque / DD Number");
        getContentPane().add(label_Cheque);
        label_Cheque.setBounds(30, 140, 130, 20);

        label_name.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_name.setForeground(new java.awt.Color(255, 255, 255));
        label_name.setText("Donor Name");
        getContentPane().add(label_name);
        label_name.setBounds(30, 180, 110, 20);

        txt_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AmountActionPerformed(evt);
            }
        });
        txt_Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_AmountKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Amount);
        txt_Amount.setBounds(170, 100, 90, 20);

        txt_Cheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ChequeKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Cheque);
        txt_Cheque.setBounds(170, 140, 90, 20);
        getContentPane().add(txt_name);
        txt_name.setBounds(170, 180, 90, 20);

        btn_Insert.setText("INSERT");
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Insert);
        btn_Insert.setBounds(40, 260, 110, 30);

        btn_Refresh.setText("REFRESH");
        btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Refresh);
        btn_Refresh.setBounds(190, 260, 110, 30);

        table_Donation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_Donation);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 100, 452, 100);

        label_DonationMainFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginbg.jpg"))); // NOI18N
        label_DonationMainFrame.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                label_DonationMainFrameComponentResized(evt);
            }
        });
        getContentPane().add(label_DonationMainFrame);
        label_DonationMainFrame.setBounds(0, 0, 790, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        setSize(800, 400);
        setLocation(100, 100);
    }//GEN-LAST:event_formComponentResized

    private void label_DonationMainFrameComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_label_DonationMainFrameComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_label_DonationMainFrameComponentResized

    private void txt_AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AmountActionPerformed

    private void txt_AmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AmountKeyTyped
       char c = evt.getKeyChar();
          if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
              evt.consume();
          }
    }//GEN-LAST:event_txt_AmountKeyTyped

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        
        double amount = Double.parseDouble(txt_Amount.getText());
        String chq  = txt_Cheque.getText();
        String name = txt_name.getText();
          try
                    { 
                            String sql = "insert into donation values (?,?,?)";
                            pst = con.prepareStatement(sql);
                            pst.setDouble(1, amount);
                            pst.setString(2, chq);

                            pst.setString(3, name);
                            pst.executeUpdate();
                            System.err.println( new Date().toString()+"::Insert Query  executed"+sql); 
                            JOptionPane.showMessageDialog(null,"Details Inserted");
                            getDonationData();
                    }
                     catch (Exception e)
                     {
                             System.out.println( new Date().toString()+"::Not Connected!!!!"+e.getMessage());
           
                     }
                     finally
                       {
                           try {
                           rs.close();
                           pst.close();
                       } 
                     catch (SQLException ex) {
                            System.out.println( new Date().toString()+"::SQL EXCEPTION"+ex.getMessage());
                            }
                      }
    }//GEN-LAST:event_btn_InsertActionPerformed

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
        txt_Amount.setText("");
        txt_Cheque.setText("");
        txt_name.setText("");
    }//GEN-LAST:event_btn_RefreshActionPerformed

    private void txt_ChequeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ChequeKeyTyped
       char c = evt.getKeyChar();
          if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
              evt.consume();
          }
    }//GEN-LAST:event_txt_ChequeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Amount;
    private javax.swing.JLabel label_Cheque;
    private javax.swing.JLabel label_DonationHeading;
    private javax.swing.JLabel label_DonationMainFrame;
    private javax.swing.JLabel label_name;
    private javax.swing.JTable table_Donation;
    private javax.swing.JTextField txt_Amount;
    private javax.swing.JTextField txt_Cheque;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
